// Named layout (split screen/picture in picture/grid/reset): put multiple visual clips into the canvas slot in one step.
// The slot rectangle is represented by the canvas fraction; the placement calculation only produces the existing ClipTransform field
// (scale/x/y/rotation/crop), the rendering layer has zero new capabilities. The math of cover relies on two established facts:
// ① The visible layer is always the entire canvas size (MediaFill width/height 100%);
// ② ClipWrapper's clip-path inset first cuts the layer, translate/rotate/scale and then moves it as a whole.
// And translate% is based on the size of the untransformed layer (=canvas), and scale is around the center of the layer.
import type { ClipCrop, ClipTransform } from './types';

/** Canvas fractional rectangle: x/y is the upper left corner, w/h is the size, both 0..1. */
export interface SlotRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

export type LayoutMode = 'cover' | 'fit';
export type PipCorner = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

export interface PipOptions {
  corner?: PipCorner;
  /** Small window side length (canvas fraction). Default 0.3, clamp to 0.1..0.6. */
  size?: number;
  /** The blank space from the small window to the edge of the canvas (canvas fraction). Default 0.04, clamp to 0..0.2. */
  margin?: number;
}

export const LAYOUT_IDS = ['full', '2up-horizontal', '2up-vertical', '3up-horizontal', 'grid-4', 'pip'] as const;
export type LayoutId = (typeof LAYOUT_IDS)[number];

const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));
const round = (v: number, digits: number): number => {
  const f = 10 ** digits;
  return Math.round(v * f) / f;
};

const STATIC_SLOTS: Record<Exclude<LayoutId, 'pip'>, Record<string, SlotRect>> = {
  full: { full: { x: 0, y: 0, w: 1, h: 1 } },
  '2up-horizontal': {
    left: { x: 0, y: 0, w: 0.5, h: 1 },
    right: { x: 0.5, y: 0, w: 0.5, h: 1 },
  },
  '2up-vertical': {
    top: { x: 0, y: 0, w: 1, h: 0.5 },
    bottom: { x: 0, y: 0.5, w: 1, h: 0.5 },
  },
  '3up-horizontal': {
    left: { x: 0, y: 0, w: 1 / 3, h: 1 },
    center: { x: 1 / 3, y: 0, w: 1 / 3, h: 1 },
    right: { x: 2 / 3, y: 0, w: 1 / 3, h: 1 },
  },
  'grid-4': {
    'top-left': { x: 0, y: 0, w: 0.5, h: 0.5 },
    'top-right': { x: 0.5, y: 0, w: 0.5, h: 0.5 },
    'bottom-left': { x: 0, y: 0.5, w: 0.5, h: 0.5 },
    'bottom-right': { x: 0.5, y: 0.5, w: 0.5, h: 0.5 },
  },
};

/** Layout → Slot table (pip is generated by parameters: main full width + inset small window in the corner). */
export function layoutSlots(layout: LayoutId, pip?: PipOptions): Record<string, SlotRect> {
  if (layout !== 'pip') return STATIC_SLOTS[layout];
  const size = clamp(pip?.size ?? 0.3, 0.1, 0.6);
  const margin = clamp(pip?.margin ?? 0.04, 0, 0.2);
  const corner = pip?.corner ?? 'bottom-right';
  const x = corner === 'top-left' || corner === 'bottom-left' ? margin : 1 - margin - size;
  const y = corner === 'top-left' || corner === 'top-right' ? margin : 1 - margin - size;
  return {
    main: { x: 0, y: 0, w: 1, h: 1 },
    inset: { x, y, w: size, h: size },
  };
}

/**
 * Calculate the ClipTransform that puts a visual layer into the slot.
 * cover: Cut the layer to the same level as the slot (no stretching, no letterbox), anchor determines which side of the source image is retained
 * (0=left/top, 0.5=center, 1=right/bottom). fit: The entire layer is indented into the letterbox groove without cutting.
 * The output always completely covers the five fields of scale/x/y/rotation/crop (rotation is returned to 0 and there is no cropping
 * crop (explicitly undefined), combined with the shallow merge of setTransform, the old layout residue can be cleared.
 */
export function placeInSlot(
  slot: SlotRect,
  mode: LayoutMode = 'cover',
  anchorX = 0.5,
  anchorY = 0.5,
): ClipTransform {
  if (!(slot.w > 0) || !(slot.h > 0) || slot.w > 1 || slot.h > 1
    || slot.x < 0 || slot.y < 0 || slot.x + slot.w > 1 + 1e-9 || slot.y + slot.h > 1 + 1e-9) {
    throw new Error(`invalid slot rect: ${JSON.stringify(slot)}`);
  }
  const slotCx = slot.x + slot.w / 2;
  const slotCy = slot.y + slot.h / 2;

  if (mode === 'fit') {
    const scale = Math.min(slot.w, slot.h);
    return {
      scale: round(scale, 6),
      // Clear non-uniform residue so layout slots stay unstretched.
      scaleX: undefined,
      scaleY: undefined,
      x: round((slotCx - 0.5) * 100, 4),
      y: round((slotCy - 0.5) * 100, 4),
      rotation: 0,
      crop: undefined,
    };
  }

  // cover: The visual window wf×hf is the same as the slot and is maximized (at least one side fills the entire layer). The zoom means that the slot is exactly filled.
  const wide = slot.w >= slot.h;
  const wf = wide ? 1 : slot.w / slot.h;
  const hf = wide ? slot.h / slot.w : 1;
  const scale = slot.w / wf; // === slot.h / hf (same construction guarantees equal value → no stretching)
  const ax = clamp(anchorX, 0, 1);
  const ay = clamp(anchorY, 0, 1);
  const left = (1 - wf) * ax;
  const top = (1 - hf) * ay;
  // After cropping, the visible center (layer coordinate fraction); scale surrounds the layer center, and translate is then filled with the canvas fraction.
  const cx = left + wf / 2;
  const cy = top + hf / 2;
  const tx = slotCx - (0.5 + (cx - 0.5) * scale);
  const ty = slotCy - (0.5 + (cy - 0.5) * scale);
  const crop: ClipCrop | undefined = wf < 1 || hf < 1
    ? {
      left: round(left, 6),
      top: round(top, 6),
      right: round(1 - wf - left, 6),
      bottom: round(1 - hf - top, 6),
    }
    : undefined;
  return {
    scale: round(scale, 6),
    scaleX: undefined,
    scaleY: undefined,
    x: round(tx * 100, 4),
    y: round(ty * 100, 4),
    rotation: 0,
    crop,
  };
}

/** The visible rectangle on the screen (canvas fraction) is deduced from the placement result - for verification: the cover mode should be exactly equal to the slot.*/
export function visibleRectOf(t: ClipTransform): SlotRect {
  const left = t.crop?.left ?? 0;
  const top = t.crop?.top ?? 0;
  const wf = 1 - left - (t.crop?.right ?? 0);
  const hf = 1 - top - (t.crop?.bottom ?? 0);
  // Layouts are uniform; axis overrides still count if a caller set them.
  const scaleX = t.scaleX ?? t.scale ?? 1;
  const scaleY = t.scaleY ?? t.scale ?? 1;
  const cx = 0.5 + (left + wf / 2 - 0.5) * scaleX + (t.x ?? 0) / 100;
  const cy = 0.5 + (top + hf / 2 - 0.5) * scaleY + (t.y ?? 0) / 100;
  return { x: cx - (wf * scaleX) / 2, y: cy - (hf * scaleY) / 2, w: wf * scaleX, h: hf * scaleY };
}
