import { useEffect, useState } from 'react';
import { sourceFramesToTimelineFrames, timelineFramesToSourceFrames } from '../editor/sourceLimit';

// Timeline clip previews: waveform peaks and video thumbnail strips. The server generates and caches
// /api/waveform and /api/filmstrip (see server/plugins/media-preview.ts); this module only handles
// src-based deduplication, in-process caching, and subscriptions, so N cuts of one asset issue one request.
// Waveforms and frame strips are generated by local ffmpeg, and the client is responsible for time mapping.

export type ClipPreviewLoadStatus = 'ready' | 'failed' | 'not-requested';

export interface ClipPreview {
  /** 0..1 amplitude envelope, peaksPerSecond per second; no audio track is an empty array */
  peaks: number[];
  peaksPerSecond: number;
  /** The real duration of the source file (not the duration after clipping) */
  durationMs: number;
  /** Video frame bar URL (video only; not ready/null on failure) */
  stripUrl: string | null;
  waveformStatus: Exclude<ClipPreviewLoadStatus, 'not-requested'>;
  filmstripStatus: ClipPreviewLoadStatus;
  waveformError?: string;
  filmstripError?: string;
}

type Entry = {
  value: ClipPreview | null;
  promise: Promise<void> | null;
  controller: AbortController | null;
  listeners: Set<() => void>;
};

const entries = new Map<string, Entry>();

/** Only local assets can be previewed (blob:/remote URL server cannot reach) */
export function isPreviewable(src: string | undefined): src is string {
  return !!src && src.startsWith('/media/uploads/');
}

function entryFor(key: string): Entry {
  let e = entries.get(key);
  if (!e) {
    e = { value: null, promise: null, controller: null, listeners: new Set() };
    entries.set(key, e);
  }
  return e;
}

type WaveResult = {
  data: { peaks?: number[]; peaksPerSecond?: number; durationMs?: number } | null;
  error?: string;
};

type StripResult = { url: string | null; error?: string };

async function responseError(response: Response): Promise<string> {
  const body = await response.json().catch(() => null) as { error?: unknown } | null;
  return typeof body?.error === 'string' ? body.error : `request failed (${response.status})`;
}

async function fetchWaveform(query: string, signal: AbortSignal): Promise<WaveResult> {
  try {
    const response = await fetch(`/api/waveform?${query}`, { signal });
    if (!response.ok) return { data: null, error: await responseError(response) };
    return { data: await response.json() as WaveResult['data'] };
  } catch (error) {
    if (signal.aborted) throw error;
    return { data: null, error: error instanceof Error ? error.message : String(error) };
  }
}

async function fetchFilmstrip(query: string, signal: AbortSignal): Promise<StripResult> {
  try {
    const url = `/api/filmstrip?${query}`;
    const response = await fetch(url, { signal });
    return response.ok ? { url } : { url: null, error: await responseError(response) };
  } catch (error) {
    if (signal.aborted) throw error;
    return { url: null, error: error instanceof Error ? error.message : String(error) };
  }
}

async function load(src: string, sourceRevision: string | undefined, wantStrip: boolean, e: Entry, signal: AbortSignal): Promise<void> {
  const query = new URLSearchParams({
    src,
    ...(sourceRevision ? { sourceRevision } : {}),
  }).toString();
  const [wave, strip] = await Promise.all([
    fetchWaveform(query, signal),
    wantStrip ? fetchFilmstrip(query, signal) : Promise.resolve<StripResult>({ url: null }),
  ]);
  if (signal.aborted) return;
  e.value = {
    peaks: wave.data?.peaks ?? [],
    peaksPerSecond: wave.data?.peaksPerSecond ?? 100,
    durationMs: wave.data?.durationMs ?? 0,
    stripUrl: strip.url,
    waveformStatus: wave.error ? 'failed' : 'ready',
    filmstripStatus: !wantStrip ? 'not-requested' : strip.error ? 'failed' : 'ready',
    ...(wave.error ? { waveformError: wave.error } : {}),
    ...(strip.error ? { filmstripError: strip.error } : {}),
  };
  for (const fn of e.listeners) fn();
}

function setLoadFailure(entry: Entry, wantStrip: boolean, error: unknown): void {
  const message = error instanceof Error ? error.message : String(error);
  entry.value = {
    peaks: [], peaksPerSecond: 100, durationMs: 0, stripUrl: null,
    waveformStatus: 'failed',
    filmstripStatus: wantStrip ? 'failed' : 'not-requested',
    waveformError: message,
    ...(wantStrip ? { filmstripError: message } : {}),
  };
  for (const listener of entry.listeners) listener();
}

/**
 * Fragment preview data. Multiple fragments of the same src share one request and one result.
 * kind determines whether frame strips are required (video only); non-native assets directly return null.
 */
export function useClipPreview(
  src: string | undefined,
  kind: string,
  sourceRevision?: string,
): ClipPreview | null {
  const key = isPreviewable(src) ? `${src}\u0000${sourceRevision ?? 'legacy'}` : '';
  const wantStrip = kind === 'video';
  const [, bump] = useState(0);

  useEffect(() => {
    if (!key) return;
    const e = entryFor(key);
    const onChange = () => bump((n) => n + 1);
    e.listeners.add(onChange);
    if (!e.value && !e.promise) {
      const controller = new AbortController();
      e.controller = controller;
      e.promise = load(src!, sourceRevision, wantStrip, e, controller.signal)
        .catch((error) => {
          if (!controller.signal.aborted) setLoadFailure(e, wantStrip, error);
        })
        .finally(() => {
          if (e.controller === controller) e.controller = null;
          e.promise = null;
        });
    }
    return () => {
      e.listeners.delete(onChange);
      if (!e.listeners.size && e.promise) {
        e.controller?.abort();
        if (entries.get(key) === e) entries.delete(key);
      }
    };
  }, [key, sourceRevision, src, wantStrip]);

  return key ? entryFor(key).value : null;
}

/**
 * Geometry mapping within fragments:
 * The clip's left edge is aligned to the source frame srcIn, and each timeline pixel is advanced by playbackRate/px of the source frame.
 * The entire frame bar covers [0, source duration), so CSS background horizontal size = source frame number × px / rate,
 * Lateral displacement = -srcIn × px / rate.
 */
export function filmstripBackground(
  preview: ClipPreview,
  { px, fps, srcInFrame, playbackRate }: { px: number; fps: number; srcInFrame: number; playbackRate: number },
): { backgroundImage: string; backgroundSize: string; backgroundPositionX: string } | null {
  if (!preview.stripUrl || !preview.durationMs) return null;
  const srcFrames = (preview.durationMs / 1000) * fps;
  const fullW = sourceFramesToTimelineFrames({ playbackRate }, srcFrames) * px;
  if (!(fullW > 0)) return null;
  return {
    backgroundImage: `url(${preview.stripUrl})`,
    backgroundSize: `${fullW.toFixed(1)}px 100%`,
    backgroundPositionX: `${(-sourceFramesToTimelineFrames({ playbackRate }, srcInFrame) * px).toFixed(1)}px`,
  };
}

/**
 * The sonic path within the clip's visible window (same mapping as the frame strip). Returns the SVG path; returns an empty string without peaks.
 * The vertical coordinate is symmetrical with height/2 as the axis, and x takes the largest peak value covered by the column column by pixel (to avoid sampling flicker).
 */
export function peaksPath(
  preview: ClipPreview,
  { widthPx, height, fps, srcInFrame, durationInFrames, playbackRate }: {
    widthPx: number; height: number; fps: number;
    srcInFrame: number; durationInFrames: number; playbackRate: number;
  },
): string {
  const { peaks, peaksPerSecond } = preview;
  if (!peaks.length || widthPx <= 0) return '';
  const cols = Math.max(1, Math.min(2000, Math.floor(widthPx / 2)));
  const mid = height / 2;
  const perFrame = peaksPerSecond / fps; // How many peaks does one source frame correspond to?
  const startIdx = srcInFrame * perFrame;
  const spanIdx = timelineFramesToSourceFrames({ playbackRate }, durationInFrames) * perFrame;
  const out: string[] = [];
  for (let c = 0; c < cols; c += 1) {
    const from = startIdx + (c / cols) * spanIdx;
    const to = startIdx + ((c + 1) / cols) * spanIdx;
    let peak = 0;
    const lo = Math.max(0, Math.floor(from));
    const hi = Math.min(peaks.length - 1, Math.max(lo, Math.ceil(to) - 1));
    for (let i = lo; i <= hi; i += 1) if (peaks[i]! > peak) peak = peaks[i]!;
    const amp = Math.max(0.5, peak * (mid - 0.5));
    const x = ((c + 0.5) / cols) * widthPx;
    out.push(`M${x.toFixed(1)} ${(mid - amp).toFixed(1)}V${(mid + amp).toFixed(1)}`);
  }
  return out.join(' ');
}
